### ISSUE TITLE
Hillside extra

### ISSUE THREAD

**Issue by yusufatmc** [Travelaps/helm-charts#11]
Pos configde değişiklik ws https://posws.elektraweb.hillsidebeachclub.com/

**Comment by yusufatmc** [comment]
Imajclip için yönlendirme
`apiVersion: v1
kind: Service
metadata:
  name: opex-survey-images
  namespace: opex
spec:
  ports:
    - name: app
      port: 8030
      protocol: TCP
      targetPort: 8030
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: opex-survey-images
  namespace: opex
subsets:
  - addresses:
      # list all external ips for this service
      - ip: 10.10.12.35
    ports:
      - name: app
        port: 8030
        protocol: TCP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: opex-survey-images
  namespace: opex
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
    nginx.ingress.kubernetes.io/server-snippet: |
      gunzip on;
      gzip on;
      gzip_disable "MSIE [1-6]\.";
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 5;
      gzip_min_length 512;
      gzip_buffers 16 128k;
      gzip_types *;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - sub.elektraweb.domain.com
      secretName: sub-elektraweb-domain-com
  rules:
    - host: sub.elektraweb.domain.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: opex-survey-images
                port:
                  number: 8030`

**Comment by yusufatmc** [comment]
Imajclip için yönlendirme
      
      apiVersion: v1
      kind: Service
      metadata:
        name: opex-survey-images
        namespace: opex
      spec:
        ports:
          - name: app
            port: 8030
            protocol: TCP
            targetPort: 8030
        clusterIP: None
        type: ClusterIP
      ---
      apiVersion: v1
      kind: Endpoints
      metadata:
        name: opex-survey-images
        namespace: opex
      subsets:
        - addresses:
            # list all external ips for this service
            - ip: 10.10.12.35
          ports:
            - name: app
              port: 8030
              protocol: TCP
      ---
      kind: Ingress
      apiVersion: networking.k8s.io/v1
      metadata:
        name: opex-survey-images
        namespace: opex
        annotations:
          kubernetes.io/ingress.class: public
          nginx.ingress.kubernetes.io/proxy-body-size: 30m
          nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
          nginx.ingress.kubernetes.io/server-snippet: |
            gunzip on;
            gzip on;
            gzip_disable "MSIE [1-6]\.";
            gzip_vary on;
            gzip_proxied any;
            gzip_comp_level 5;
            gzip_min_length 512;
            gzip_buffers 16 128k;
            gzip_types *;
          nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      spec:
        tls:
          - hosts:
              - sub.elektraweb.domain.com
            secretName: sub-elektraweb-domain-com
        rules:
          - host: sub.elektraweb.domain.com
            http:
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: opex-survey-images
                      port:
                        number: 8030

**Comment by yusufatmc** [comment]
add callcenterintegration


```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: call-center-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: call-center-integration
  template:
    metadata:
      name: call-center-integration
      creationTimestamp: null
      labels:
        k8s-app: call-center-integration
    spec:
      containers:
        - name: call-center-integration
          image: ghcr.io/travelaps/call-center-integration:v20
          env:
            - name: APIURL
              value: https://api.hillsidebeachclub.com
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: call-center-integration
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    k8s-app: call-center-integration
  type: ClusterIP
  sessionAffinity: None
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: call-center-integration-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/cors-max-age: '600'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/limit-rpm: '5'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
spec:
  tls:
    - hosts:
        - callcenterintegration.elektraweb.hillsidebeachclub.com 
      secretName: callcenterintegration-elektraweb-com-cert
  rules:
    - host: callcenterintegration.elektraweb.hillsidebeachclub.com 
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: call-center-integration
                port:
                  number: 8000
```
