### ISSUE TITLE
wildcard ssl extra

### ISSUE THREAD

**Issue by yusufatmc** [Travelaps/helm-charts#18]
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cloudflare
spec:
  acme:
    email: ssl@elektraweb.com
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token-secret
```
---
`
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-elektraweb-dev-cert
  namespace: cert-manager
spec:
  dnsNames:
    - '*.elektraweb.dev'
    - elektraweb.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-cloudflare
  secretName: wildcard-elektraweb-dev-cert
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
  usages:
    - digital signature
    - key encipherment
`
